inherit_from: configs/Synthetic/synthetic.yaml
mapping:
  first_mesh: False
  bound: [[-2.6, 5.6],[-0.3, 3.0],[0.2, 5.1]]
  marching_cubes_bound: [[-2.6, 5.6],[-0.3, 3.0],[0.2, 5.1]]
  

data:
  datadir: ../data/neural_rgbd_data/green_room
  trainskip: 1
  output: output/Synthetic/gr
  exp_name: 19_base

cam:
  near: 0
  far: 8

mesh:
  vis: 1000000000
  visualisation: False

timing:
  mode: none
  warmup_frames: 0
  max_frames: null
  disable_eval: True
  scene_output_csv: ./results/layer_timing/Synthetic/gr_scene_rep_timing.csv
  coslam_output_csv: ./results/layer_timing/Synthetic/gr_coslam_layer_timing.csv
  frame_total_output_csv: ./results/frame_total/Synthetic/gr_frame_total_timing_complete_pruning.csv
  frame_total_write_header: False
