inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-3,3],[-4,2.5],[-2,2.5]]
  marching_cubes_bound: [[-2.2,2.6],[-3.4,2.1],[-1.4,2.0]]
  

data:
  datadir: ../data/Replica/office0
  trainskip: 1
  output: output/Replica/office0_2
  exp_name: "morton_R128_13"

# Add profiling config here
profiling:
  enabled: true
  output_dir: ./profiling/PytorchProfiler/office0
  schedule:
    wait: 1
    warmup: 0
    active: 10
    repeat: 1