inherit_from: configs/Replica/replica.yaml
mapping:
  first_mesh: False
  bound: [[-3,3],[-4,2.5],[-2,2.5]]
  marching_cubes_bound: [[-2.2,2.6],[-3.4,2.1],[-1.4,2.0]]
  

data:
  datadir: ../data/Replica/office0
  trainskip: 1
  output: output/Replica/office0
  exp_name: "complete_pruning"

mesh:
  vis: 1000000000
  visualisation: False

timing:
  mode: frame_total # options: none, scene_rep, coslam, frame_total
  warmup_frames: 1
  max_frames: null
  disable_eval: True
  scene_output_csv: ./office0_scene_rep_timing_complete_pruningD.csv
  coslam_output_csv: ./office0_coslam_layer_timing_complete_pruningD.csv
  frame_total_output_csv: ./office0_frame_total_timing_complete_pruning.csv
  frame_total_write_header: False

# Add profiling config here
profiling:
  enabled: False
  output_dir: ./profiling/PytorchProfiler/office0
  schedule:
    wait: 1
    warmup: 0
    active: 10
    repeat: 1
