inherit_from: configs/Replica/replica.yaml
mapping:
  first_mesh: False
  bound: [[-5.3,3.7],[-6.1,3.4],[-1.4,2.0]]
  marching_cubes_bound: [[-5.2,3.6],[-6.0,3.3],[-1.3,1.9]]

  

data:
  datadir: ../datasets/data/Replica/office3
  trainskip: 1
  output: output/Replica/office3
  exp_name: "bucket"

mesh:
  vis: 1000000000
  visualisation: False

timing:
  mode: none   # options: none, scene_rep, coslam
  warmup_frames: 0
  max_frames: 2000
  disable_eval: True
  scene_output_csv: ./office3_scene_rep_timing_cropped.csv
  coslam_output_csv: ./office3_coslam_layer_timing_cropped.csv

# Add profiling config here
profiling:
  enabled: False
  output_dir: ./profiling/PytorchProfiler/office3
  schedule:
    wait: 1
    warmup: 0
    active: 10
    repeat: 1