inherit_from: configs/Replica/replica.yaml
mapping:
  first_mesh: False
  bound: [[-2,3.2],[-1.7,2.7],[-1.2,2.0]]
  marching_cubes_bound: [[-1.9,3.1],[-1.6,2.6],[-1.1,1.8]]
  


data:
  datadir: ../datasets/data/Replica/office1
  trainskip: 1
  output: output/Replica/office1
  exp_name: "bucket"

mesh:
  vis: 1000000000
  visualisation: False

timing:
  mode: none   # options: none, scene_rep, coslam
  warmup_frames: 0
  max_frames: 2000
  disable_eval: True
  scene_output_csv: ./office1_scene_rep_timing_cropped.csv
  coslam_output_csv: ./office1_coslam_layer_timing_cropped.csv

# Add profiling config here
profiling:
  enabled: False
  output_dir: ./profiling/PytorchProfiler/office1
  schedule:
    wait: 1
    warmup: 0
    active: 10
    repeat: 1