inherit_from: configs/Replica/replica.yaml
mapping:
  first_mesh: False
  bound: [[-5.6,1.4],[-3.2,2.8],[-1.6,1.8]]
  marching_cubes_bound: [[-5.6,1.4],[-3.2,2.8],[-1.6,1.8]]


data:
  datadir: ../datasets/data/Replica/room1
  trainskip: 1
  output: output/Replica/room1
  exp_name: "bucket"

mesh:
  vis: 1000000000
  visualisation: False

timing:
  mode: none   # options: none, scene_rep, coslam
  warmup_frames: 0
  max_frames: 2000
  disable_eval: True
  scene_output_csv: ./room1_scene_rep_timing_cropped.csv
  coslam_output_csv: ./room1_coslam_layer_timing_cropped.csv

# Add profiling config here
profiling:
  enabled: False
  output_dir: ./profiling/PytorchProfiler/room1
  schedule:
    wait: 1
    warmup: 0
    active: 10
    repeat: 1