inherit_from: configs/Replica/replica.yaml
mapping:
  first_mesh: False
  bound: [[-1.0,6.1],[-3.4,1.9],[-3.1,0.8]]
  marching_cubes_bound: [[-0.9,6.0],[-3.3,1.8],[-3.0,0.7]]


data:
  datadir: ../datasets/data/Replica/room2
  trainskip: 1
  output: output/Replica/room2
  exp_name: "bucket"

mesh:
  vis: 1000000000
  visualisation: False

timing:
  mode: none   # options: none, scene_rep, coslam
  warmup_frames: 0
  max_frames: 2000
  disable_eval: True
  scene_output_csv: ./room2_scene_rep_timing_cropped.csv
  coslam_output_csv: ./room2_coslam_layer_timing_cropped.csv

# Add profiling config here
profiling:
  enabled: False
  output_dir: ./profiling/PytorchProfiler/room2
  schedule:
    wait: 1
    warmup: 0
    active: 10
    repeat: 1