inherit_from: configs/Replica/replica.yaml
mapping:
  first_mesh: False
  bound: [[-1.0,7.0],[-1.3,3.7],[-1.7,1.4]]
  marching_cubes_bound: [[-1.0,7.0],[-1.3,3.7],[-1.7,1.4]]


data:
  datadir: ../datasets/data/Replica/room0
  trainskip: 1
  output: output/Replica/room0
  exp_name: "quality"

mesh:
  vis: 1000000000
  visualisation: False

timing:
  mode: coslam   # options: none, scene_rep, coslam
  warmup_frames: 11
  max_frames: 60
  disable_eval: True
  scene_output_csv: ./room0_scene_rep_timing_cropped.csv
  coslam_output_csv: ./room0_coslam_layer_timing_cropped.csv

# Add profiling config here
profiling:
  enabled: False
  output_dir: ./profiling/PytorchProfiler/room0
  schedule:
    wait: 1
    warmup: 0
    active: 10
    repeat: 1