inherit_from: configs/Replica/replica.yaml
mapping:
  first_mesh: False
  bound: [[-1.0,7.0],[-1.3,3.7],[-1.7,1.4]]
  marching_cubes_bound: [[-1.0,7.0],[-1.3,3.7],[-1.7,1.4]]


data:
  datadir: ../data/Replica/room0
  trainskip: 1
  output: output/Replica/room0
  exp_name: "17"

mesh:
  vis: 1000000000
  visualisation: False

timing:
  mode: none   # options: none, scene_rep, coslam
  warmup_frames: 0
  max_frames: null
  disable_eval: True
  scene_output_csv: ./Monitoring/multilayer/room0/scene_rep_timing_A.csv
  coslam_output_csv: ./Monitoring/multilayer/room0/coslam_layer_timing_A.csv
